
export const PostsTypes = {
    INIT_POSTS: "INIT_POSTS",
    SUCCES_POSTS: "SUCCES_POSTS",
    SET_POSTS: "SET_POSTS",
    DELETE_POST: "DELETE_POST", 
    CLEAR_NEWS: "CLEAR_NEWS",
    ERROR_NEWS: "ERROR_NEWS",
}